version: '2'

services:
  front:
    build: ./front
    image: ghcr.io/tinf21cs1/dhbw-vorlesungsplan2-front:develop
    ports:
      - "80:80"
    networks:
      - db

  api:
    build: ./api
    image: ghcr.io/tinf21cs1/dhbw-vorlesungsplan2-api:develop
    env_file:
      - ./api/.env.dev
    networks:
      - db

  ical:
    build: ./ical-parser
    image: ghcr.io/tinf21cs1/dhbw-vorlesungsplan2-ical:develop
    env_file:
      - ./ical-parser/.env.dev
    networks:
      - db
    depends_on:
      mongosetup:
        condition: service_completed_successfully

  mongo:
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./db/data:/data/db
    networks:
      - db
  mongosetup:
    image: mongo:4.2.8
    depends_on:
      - mongo
    restart: "no"
    entrypoint:
      [
        "bash",
        "-c",
        "sleep 10 && mongo --host mongo:27017 --eval \"rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo:27017'}]});\" && sleep 10 && mongo --host mongo:27017 --eval \"db.getSiblingDB('calendar').createUser({user: 'vp2', pwd: 'vp2', roles: ['readWrite']})\" && mongo --host mongo:27017 --eval \"db.getSiblingDB('users').createUser({user: 'vp2', pwd: 'vp2', roles: ['readWrite']})\"|| true"
      ]
    networks:
      - db
networks:
  db:
