version: '2'

services:
  front:
    image: ghcr.io/tinf21cs1/dhbw-vorlesungsplan2-front:latest
    ports:
      - "80:80"
  
  api:
    image: ghcr.io/tinf21cs1/dhbw-vorlesungsplan2-api:latest

  mongo:
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./db/data:/data/db
    networks:
      - db
  mongosetup:
    image: mongo:4.2.8
    depends_on:
      - mongo
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 10 && mongo --host mongo:27017 --eval \"rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]});\""]  
    networks:
      - db
networks:
  db:
