# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main, develop]
    tags: ["v*"]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: GENERATE_SOURCEMAP=false yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build
      - name: Create build.zip archive
        run: cd ./build/ && zip -r ../build.zip *
      - name: Create build.tar.gz archive
        run: cd ./build && tar -czvf ../build.tar.gz *
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ./build.zip
            ./build.tar.gz
